// <auto-generated />
using System;
using Infra.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infra.Migrations
{
    [DbContext(typeof(AvaliacaoContexto))]
    [Migration("20200429052620_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dominio.Entidades.Anuncio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cor")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataDeVenda")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModeloId")
                        .HasColumnType("int");

                    b.Property<int>("TipoDeCombustivel")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorDeCompra")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorDeVenda")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ModeloId");

                    b.ToTable("Anuncio");
                });

            modelBuilder.Entity("Dominio.Entidades.Modelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ano")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.ToTable("Modelo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ano = "2000",
                            MarcaId = 1,
                            Nome = "Corsa"
                        },
                        new
                        {
                            Id = 2,
                            Ano = "2005",
                            MarcaId = 1,
                            Nome = "Corsa"
                        },
                        new
                        {
                            Id = 3,
                            Ano = "2009",
                            MarcaId = 1,
                            Nome = "Corsa"
                        },
                        new
                        {
                            Id = 4,
                            Ano = "2000",
                            MarcaId = 1,
                            Nome = "Montana"
                        },
                        new
                        {
                            Id = 5,
                            Ano = "2005",
                            MarcaId = 1,
                            Nome = "Montana"
                        },
                        new
                        {
                            Id = 6,
                            Ano = "2009",
                            MarcaId = 1,
                            Nome = "Montana"
                        },
                        new
                        {
                            Id = 7,
                            Ano = "2001",
                            MarcaId = 2,
                            Nome = "Uno"
                        },
                        new
                        {
                            Id = 8,
                            Ano = "2011",
                            MarcaId = 2,
                            Nome = "Uno"
                        },
                        new
                        {
                            Id = 9,
                            Ano = "2015",
                            MarcaId = 2,
                            Nome = "Uno"
                        },
                        new
                        {
                            Id = 10,
                            Ano = "2001",
                            MarcaId = 2,
                            Nome = "Fiorino"
                        },
                        new
                        {
                            Id = 11,
                            Ano = "2015",
                            MarcaId = 2,
                            Nome = "Fiorino"
                        },
                        new
                        {
                            Id = 12,
                            Ano = "2016",
                            MarcaId = 2,
                            Nome = "Fiorino"
                        },
                        new
                        {
                            Id = 13,
                            Ano = "2001",
                            MarcaId = 3,
                            Nome = "Fiesta"
                        },
                        new
                        {
                            Id = 14,
                            Ano = "2005",
                            MarcaId = 3,
                            Nome = "Fiesta"
                        },
                        new
                        {
                            Id = 15,
                            Ano = "2007",
                            MarcaId = 3,
                            Nome = "Fiesta"
                        },
                        new
                        {
                            Id = 16,
                            Ano = "2016",
                            MarcaId = 3,
                            Nome = "Ranger"
                        },
                        new
                        {
                            Id = 17,
                            Ano = "2018",
                            MarcaId = 3,
                            Nome = "Ranger"
                        },
                        new
                        {
                            Id = 18,
                            Ano = "2019",
                            MarcaId = 3,
                            Nome = "Ranger"
                        },
                        new
                        {
                            Id = 19,
                            Ano = "2014",
                            MarcaId = 4,
                            Nome = "Civic"
                        },
                        new
                        {
                            Id = 20,
                            Ano = "2016",
                            MarcaId = 4,
                            Nome = "Civic"
                        },
                        new
                        {
                            Id = 21,
                            Ano = "2018",
                            MarcaId = 4,
                            Nome = "Civic"
                        },
                        new
                        {
                            Id = 22,
                            Ano = "2009",
                            MarcaId = 4,
                            Nome = "CRV"
                        },
                        new
                        {
                            Id = 23,
                            Ano = "2010",
                            MarcaId = 4,
                            Nome = "CRV"
                        },
                        new
                        {
                            Id = 24,
                            Ano = "2019",
                            MarcaId = 4,
                            Nome = "CRV"
                        });
                });

            modelBuilder.Entity("Entidades.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Marca");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Chevrolet"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Fiat"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Ford"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Honda"
                        });
                });

            modelBuilder.Entity("Dominio.Entidades.Anuncio", b =>
                {
                    b.HasOne("Dominio.Entidades.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Entidades.Modelo", b =>
                {
                    b.HasOne("Entidades.Marca", "Marca")
                        .WithMany("Modelos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
